
SMOKE_TEST = True
BATCH_SIZE = 4
NUM_RESTARTS = 10 if not SMOKE_TEST else 1
RAW_SAMPLES = 512 if not SMOKE_TEST else 1

N_BATCH = 70 if not SMOKE_TEST else 1
MC_SAMPLES = 128 if not SMOKE_TEST else 1
verbose = True

# SEEDS = [0,1,2,3,4,5,6,7,8,9] TODO METER ESTA LISTA COMO ARGS DEL JSON